apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - migration-job.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - platform/clusterissuer.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: taskapp
