apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: taskapp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: taskapp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
