apiVersion: v1
kind: Secret
metadata:
  name: taskapp-secret
  namespace: taskapp
type: Opaque
stringData:
  DB_USER: "set-locally"
  DB_PASSWORD: "set-locally"
  DATABASE_USER: "set-locally"
  DATABASE_PASSWORD: "set-locally"
  SECRET_KEY: "set-locally"
  DATABASE_URL: "postgresql://set-locally:set-locally@postgres:5432/taskapp"
