apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/soyoyeolayinka/capstone-phoenix.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: taskapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: postgres
      namespace: taskapp
      jsonPointers:
        - /spec/volumeClaimTemplates
